services:
  docs:
    image: rapidconsult_local_docs
    container_name: rapidconsult_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./rapidconsult:/app/rapidconsult:z
    ports:
      - '9000:9000'
    command: /start-docs
