# Generated by Django 5.0.6 on 2025-08-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_userorgprofile_role_alter_userorgprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorgprofile',
            name='allowed_locations',
            field=models.ManyToManyField(blank=True, related_name='permitted_users', to='scheduling.location'),
        ),
    ]
