# Generated by Django 5.0.6 on 2025-09-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_userorgprofile_allowed_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='oncallshift',
            name='shift_type',
            field=models.CharField(blank=True, choices=[('oncall', 'On-Call'), ('outpatient', 'Out-Patient')], default='oncall', help_text='Type of shift: oncall or outpatient', max_length=20, null=True),
        ),
    ]
