# Generated by Django 5.0.6 on 2025-10-16 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='scheduling.department'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='scheduling.location'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='scheduling.organization'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='scheduling.unit'),
        ),
    ]
