# Generated by Django 5.0.6 on 2025-07-23 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=25, null=True)),
                ('country_code', models.CharField(blank=True, help_text='e.g. +91', max_length=6, null=True)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('verified', models.BooleanField(blank=True, default=False, null=True)),
                ('primary', models.BooleanField(blank=True, default=False, null=True)),
                ('type', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('home', 'Home'), ('work', 'Work'), ('fax', 'Fax'), ('other', 'Other'), ('email', 'Email'), ('on_call', 'On Call'), ('clinic', 'Clinic')], default='mobile', max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
