# Generated by Django 5.0.6 on 2025-12-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='device_type',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Device Type'),
        ),
    ]
